application: foodiprototype01
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /stylesheets
  static_dir: stylesheets

- url: /images
  static_dir: images

- url: /scripts
  static_dir: scripts

 # Handler for front page
- url: /
  script: guestbook.application

- url: /sign
  script: guestbook.application

- url: /About
  script: guestbook.application

- url: /Contact
  script: guestbook.application

- url: /Privacy
  script: guestbook.application

- url: /.*
  script: guestbook.application
  login: required


libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest